const { goals } = require('mineflayer-pathfinder');
const sleep = ms => new Promise(r => setTimeout(r, ms));
const LOGS=['oak_log','birch_log','spruce_log','jungle_log','acacia_log','dark_oak_log','mangrove_log','cherry_log'];
const LEAVES=['oak_leaves','birch_leaves','spruce_leaves','jungle_leaves','acacia_leaves','dark_oak_leaves','mangrove_leaves','cherry_leaves','azalea_leaves','flowering_azalea_leaves'];
const PLANKS=['oak_planks','birch_planks','spruce_planks','jungle_planks','acacia_planks','dark_oak_planks','mangrove_planks','cherry_planks'];
function findBlock(bot,names,maxDistance=48){const s=new Set(names);return bot.findBlock({matching:b=>b&&s.has(b.name),maxDistance});}
function findTreeLog(bot,maxDistance=48){const cs=bot.findBlocks({matching:b=>b&&LOGS.includes(b.name),maxDistance,count:80});const o=bot.entity?.position;if(!o)return null;let best=null,score=Infinity;for(const pos of cs){const log=bot.blockAt(pos);if(!log)continue;const leaves=bot.findBlocks({matching:b=>b&&LEAVES.includes(b.name),maxDistance:5,count:20,point:pos});if(!leaves.length)continue;const d=o.distanceTo(pos),s=d+Math.max(0,4-leaves.length)*2;if(s<score){score=s;best=log;}}return best;}
function inventoryCount(bot,names){return bot.inventory.items().filter(i=>names.includes(i.name)).reduce((n,i)=>n+i.count,0);}
function reportInventory(bot,label){const items=bot.inventory.items().map(i=>`${i.name} x${i.count}`);console.log(`[INVENTORY] ${label}: ${items.length?items.join(', '):'empty'}`);return items;}
function firstRecipe(bot,output){const item=bot.registry.itemsByName[output];return item?(bot.recipesFor(item.id,null,1,null)[0]||null):null;}
async function craft(bot,output,count=1){const r=firstRecipe(bot,output);if(!r)return false;try{await bot.craft(r,count,null);return true;}catch(e){console.warn(`Craft ${output} failed: ${e.message}`);return false;}}
async function collectLogs(bot,amount=8){const before=inventoryCount(bot,LOGS);for(let i=0;i<amount;i++){const b=findTreeLog(bot);if(!b)break;try{bot.autonomyBusy=true;await bot.collectBlock.collect(b);}catch(e){console.warn(`Wood collection failed: ${e.message}`);break;}finally{bot.autonomyBusy=false;}}const gain=Math.max(0,inventoryCount(bot,LOGS)-before);reportInventory(bot,'after wood');return gain;}
async function collectStone(bot,amount=12){const before=inventoryCount(bot,['stone','cobblestone']);for(let i=0;i<amount;i++){const b=findBlock(bot,['stone'],32);if(!b)break;try{bot.autonomyBusy=true;await bot.collectBlock.collect(b);}catch(e){console.warn(`Stone collection failed: ${e.message}`);break;}finally{bot.autonomyBusy=false;}}const gain=Math.max(0,inventoryCount(bot,['stone','cobblestone'])-before);reportInventory(bot,'after stone');return gain;}
async function starter(bot){if(bot.autonomyStarted)return;bot.autonomyStarted=true;bot.autonomyStage='finding_tree';bot.chat('Začínam survival: hľadám prirodzený strom.');await sleep(1200);const logs=await collectLogs(bot,8);if(!logs){bot.autonomyStage='waiting_for_tree';bot.chat('Nenašiel som prirodzený strom. Stavby rozoberať nebudem.');return;}bot.chat(`Overené: v inventári pribudlo ${logs} drevo.`);const log=bot.inventory.items().find(i=>LOGS.includes(i.name));if(!log){bot.chat('Drevo sa po ťažbe neobjavilo v inventári, crafting nespúšťam.');return;}bot.autonomyStage='crafting_wood';await craft(bot,log.name.replace('_log','_planks'),Math.min(4,log.count*4));if(inventoryCount(bot,PLANKS)>=4)await craft(bot,'crafting_table');if(inventoryCount(bot,['stick'])<4)await craft(bot,'stick',2);await craft(bot,'wooden_pickaxe');reportInventory(bot,'after wood tools');if(bot.inventory.items().some(i=>i.name==='wooden_pickaxe')){bot.autonomyStage='mining_stone';bot.chat('Drevený krompáč je v inventári. Hľadám kameň.');const stone=await collectStone(bot,12);if(stone>0){await craft(bot,'stone_pickaxe');await craft(bot,'stone_axe');await craft(bot,'stone_shovel');bot.autonomyStage='starter_complete';bot.chat(`Starter hotový. Reálne som získal ${stone} kameňov.`);reportInventory(bot,'starter complete');}else bot.chat('Kameň som nezískal, takže netvrdím, že ho mám.');}}
function startHumanMovement(bot){const timer=setInterval(()=>{if(!bot.entity||bot.pathfinder.isMoving()||bot.pvp?.target||bot.autonomyBusy)return;if(Math.random()>0.65)return;const p=bot.entity.position;bot.pathfinder.setGoal(new goals.GoalNear(p.x+Math.random()*12-6,p.y,p.z+Math.random()*12-6,2));},4500);bot.once('end',()=>clearInterval(timer));}
module.exports={starter,startHumanMovement,reportInventory};