const { goals } = require('mineflayer-pathfinder');
const sleep = ms => new Promise(r => setTimeout(r, ms));
const LOGS=['oak_log','birch_log','spruce_log','jungle_log','acacia_log','dark_oak_log','mangrove_log','cherry_log'];
const LEAVES=['oak_leaves','birch_leaves','spruce_leaves','jungle_leaves','acacia_leaves','dark_oak_leaves','mangrove_leaves','cherry_leaves','azalea_leaves','flowering_azalea_leaves'];
const PLANKS=['oak_planks','birch_planks','spruce_planks','jungle_planks','acacia_planks','dark_oak_planks','mangrove_planks','cherry_planks'];
const sleepSafe=ms=>new Promise(r=>setTimeout(r,ms));
function count(bot,names){return bot.inventory.items().filter(i=>names.includes(i.name)).reduce((n,i)=>n+i.count,0);}
function findBlock(bot,names,maxDistance=48){const s=new Set(names);return bot.findBlock({matching:b=>b&&s.has(b.name),maxDistance});}
function findTreeLog(bot,maxDistance=48){const origin=bot.entity?.position;if(!origin)return null;const candidates=bot.findBlocks({matching:b=>b&&LOGS.includes(b.name),maxDistance,count:100});let best=null,bestScore=Infinity;for(const pos of candidates){const log=bot.blockAt(pos);if(!log)continue;const leaves=bot.findBlocks({matching:b=>b&&LEAVES.includes(b.name),maxDistance:5,count:30,point:pos});if(!leaves.length)continue;const d=origin.distanceTo(pos);const score=d+(leaves.length<3?8:0);if(score<bestScore){bestScore=score;best=log;}}return best;}
function reportInventory(bot,label){const items=bot.inventory.items().map(i=>`${i.name} x${i.count}`);console.log(`[INVENTORY] ${label}: ${items.length?items.join(', '):'empty'}`);return items;}
function recipe(bot,output){const item=bot.registry.itemsByName[output];return item?(bot.recipesFor(item.id,null,1,null)[0]||null):null;}
async function craft(bot,output,craftCount=1){const r=recipe(bot,output);if(!r)return false;let table=null;if(r.requiresTable)table=bot.findBlock({matching:b=>b&&b.name==='crafting_table',maxDistance:8});if(r.requiresTable&&!table){console.warn(`Craft ${output}: no crafting table nearby`);return false;}try{const before=count(bot,[output]);await bot.craft(r,craftCount,table);return count(bot,[output])>before;}catch(e){console.warn(`Craft ${output} failed: ${e.message}`);return false;}}
async function collectOne(bot,block){if(!block)return false;try{bot.autonomyBusy=true;await bot.collectBlock.collect(block);return true;}catch(e){console.warn(`Collect failed: ${e.message}`);return false;}finally{bot.autonomyBusy=false;}}
async function collectLogs(bot,target=8){const before=count(bot,LOGS);let misses=0;while(count(bot,LOGS)-before<target&&misses<3){const block=findTreeLog(bot);if(!block){misses++;await sleepSafe(800);continue;}if(!(await collectOne(bot,block)))misses++;}const gain=Math.max(0,count(bot,LOGS)-before);reportInventory(bot,'after wood');return gain;}
async function collectStone(bot,target=12){const before=count(bot,['cobblestone','stone']);let misses=0;while(count(bot,['cobblestone','stone'])-before<target&&misses<3){const block=findBlock(bot,['stone'],32);if(!block){misses++;break;}if(!(await collectOne(bot,block)))misses++;}const gain=Math.max(0,count(bot,['cobblestone','stone'])-before);reportInventory(bot,'after stone');return gain;}
async function starter(bot){if(bot.autonomyStarted)return;bot.autonomyStarted=true;bot.autonomyStage='finding_tree';bot.chat('Začínam survival: hľadám prirodzený strom.');await sleepSafe(1000);const gained=await collectLogs(bot,8);if(!gained){bot.autonomyStage='waiting_for_tree';bot.chat('Nenašiel som prirodzený strom. Stavby rozoberať nebudem.');return;}bot.chat(`Overené: v inventári pribudlo ${gained} drevo.`);const log=bot.inventory.items().find(i=>LOGS.includes(i.name));if(!log)return bot.chat('Drevo nie je v inventári, crafting nespúšťam.');bot.autonomyStage='crafting_wood';const plankName=log.name.replace('_log','_planks');await craft(bot,plankName,Math.min(log.count,4));if(count(bot,PLANKS)>=4){await craft(bot,'crafting_table');}const table=bot.findBlock({matching:b=>b&&b.name==='crafting_table',maxDistance:8});if(!table){bot.chat('Crafting table sa nepodarilo vytvoriť/nájsť.');return;}if(count(bot,['stick'])<4)await craft(bot,'stick',2);await craft(bot,'wooden_pickaxe');reportInventory(bot,'after wood tools');if(!bot.inventory.items().some(i=>i.name==='wooden_pickaxe')){bot.chat('Drevený krompáč sa nevytvoril, takže mining nespúšťam.');return;}bot.autonomyStage='mining_stone';bot.chat('Drevený krompáč je v inventári. Hľadám kameň.');const stone=await collectStone(bot,12);if(!stone)return bot.chat('Kameň som nezískal, takže netvrdím, že ho mám.');await craft(bot,'stone_pickaxe');await craft(bot,'stone_axe');await craft(bot,'stone_shovel');bot.autonomyStage='starter_complete';bot.chat(`Starter hotový. Reálne som získal ${stone} kameňa.`);reportInventory(bot,'starter complete');}
function startHumanMovement(bot){if(bot.humanMovementStarted)return;bot.humanMovementStarted=true;const timer=setInterval(()=>{if(!bot.entity||bot.pathfinder.isMoving()||bot.pvp?.target||bot.autonomyBusy||bot.followingPlayer)return;if(Math.random()>0.65)return;const p=bot.entity.position;const below=bot.blockAt(p.offset(0,-1,0));if(!below||['air','cave_air','void_air','lava'].includes(below.name))return;const a=Math.random()*Math.PI*2,d=3+Math.random()*9;bot.pathfinder.setGoal(new goals.GoalNear(p.x+Math.cos(a)*d,p.y,p.z+Math.sin(a)*d,2));},4500);bot.once('end',()=>clearInterval(timer));}
module.exports={starter,startHumanMovement,reportInventory,count,findTreeLog};
