const mineflayer=require('mineflayer');
const {pathfinder,Movements,goals}=require('mineflayer-pathfinder');
const {loadGameplay,registerCommands}=require('./gameplay');
const {starter,startHumanMovement}=require('./autonomy');
const {registerAIBrain}=require('./ai-brain');
const {startHumanBehavior,registerHumanEvents}=require('./human-behavior');
const {loadMemory,saveMemory}=require('./memory');
const {startGoalManager,registerGoalCommands}=require('./goal-manager');

function createSafeMovements(bot){const m=new Movements(bot);m.maxDropDown=1;m.allowParkour=false;m.allow1by1towers=false;m.canDig=true;m.canOpenDoors=true;m.canUseDoors=true;m.liquidCost=8;m.emptyCost=1;m.lavaCost=1000;m.waterCost=8;m.mobCost=20;return m;}
function followPlayer(bot,username){const t=bot.players[username]?.entity;if(!t)return bot.chat('Nevidím ťa.');bot.followingPlayer=username;bot.pathfinder.setMovements(createSafeMovements(bot));bot.pathfinder.setGoal(new goals.GoalNear(t.position.x,t.position.y,t.position.z,2),true);bot.chat('Idem za tebou a priebežne hľadám bezpečnú trasu.');}
function stopBot(bot){bot.followingPlayer=null;bot.pathfinder.setGoal(null);bot.clearControlStates();if(bot.pvp)bot.pvp.stop();bot.currentGoal='idle';}
function status(bot){const p=bot.entity?.position;const inv=bot.inventory.items().map(i=>`${i.name} x${i.count}`).join(', ')||'empty';bot.chat(`HP ${bot.health} | food ${bot.food} | goal ${bot.currentGoal||'unknown'} | stage ${bot.autonomyStage||'unknown'} | ${p?`${p.x.toFixed(0)},${p.y.toFixed(0)},${p.z.toFixed(0)}`:'no-pos'} | inv: ${inv.slice(0,180)}`);}
function startBot(config){let reconnectTimer=null, ended=false;console.log(`[${config.username}] Connecting to ${config.host}:${config.port}...`);const bot=mineflayer.createBot({host:config.host,port:config.port,username:config.username,auth:config.auth||'offline',version:config.version||false});bot.loadPlugin(pathfinder);bot.memory=loadMemory(bot);loadGameplay(bot);
 bot.once('spawn',async()=>{console.log(`[${bot.username}] joined.`);bot.pathfinder.setMovements(createSafeMovements(bot));bot.chat('Ahoj! Som SurvivalCraftAI.');startHumanMovement(bot);startHumanBehavior(bot);registerHumanEvents(bot);startGoalManager(bot);registerGoalCommands(bot);await starter(bot);});
 bot.on('chat',(username,message)=>{if(username===bot.username)return;const text=message.trim().toLowerCase();if(text==='!help')return bot.chat('!follow !come !stop !pos !status !inventory !eat !fight !build !mine <block> !goal !sethome !home !remember');if(text==='!pos'){const p=bot.entity?.position;if(!p)return bot.chat('Ešte nemám pozíciu.');return bot.chat(`Pozícia: ${p.x.toFixed(1)}, ${p.y.toFixed(1)}, ${p.z.toFixed(1)} | HP ${bot.health} | food ${bot.food}`);}if(text==='!status'||text==='!inventory')return status(bot);if(text==='!stop'){stopBot(bot);return bot.chat('Zastavujem.');}if(text==='!come'||text==='!follow')followPlayer(bot,username);});
 registerCommands(bot);registerAIBrain(bot);const followTimer=setInterval(()=>{if(!bot.followingPlayer||!bot.entity)return;const t=bot.players[bot.followingPlayer]?.entity;if(!t)return;if(bot.entity.position.distanceTo(t.position)>4){bot.pathfinder.setMovements(createSafeMovements(bot));bot.pathfinder.setGoal(new goals.GoalNear(t.position.x,t.position.y,t.position.z,2),true);}},900);bot.once('end',()=>{ended=true;clearInterval(followTimer);saveMemory(bot);});bot.on('kicked',r=>console.log(`[${bot.username}] Kicked:`,r));bot.on('error',e=>console.error(`[${bot.username}] Error:`,e.message));bot.on('death',()=>{bot.memory.deaths=(bot.memory.deaths||0)+1;saveMemory(bot);});bot.on('end',()=>{if(ended)return;console.log(`[${bot.username}] Disconnected. Reconnecting...`);clearTimeout(reconnectTimer);reconnectTimer=setTimeout(()=>startBot(config),config.reconnectDelayMs||5000);});return bot;}
module.exports={startBot};
